### ISSUE TITLE
1.19.2 fabric

### ISSUE THREAD

**Issue by MOOOOs** [Kotori316/LimitMobSpawn-fabric#1]
1.19.2 fabric support?

**Comment by Kotori316** [comment]
https://www.curseforge.com/minecraft/mc-mods/limit-mob-spawn/files/3974422

**Comment by MOOOOs** [comment]
That file doesn't exist

**Comment by Kotori316** [comment]
Just wait a moment, please.
The file is under review in the CurseForge process.

2022年9月9日(金) 11:02 MOOOOs ***@***.***>:
